### ISSUE TITLE
Uncaught Error: Call to a member function create() on null in  

### ISSUE THREAD

**Issue by matinict** [baddwin/magento2-ongkir#1] opened 2018-08-12 09:35 UTC
use Magento\Framework\HTTP\ZendClientFactory; 

Uncaught Error: Call to a member function create() on null in  app/code/Amzone/Ongkir/Model/Query/Api.php:23

**Comment by baddwin** [comment] 2018-08-13 01:37
Please clear your cache first, and then run `php bin/magento setup:di:compile`

**Comment by kipotlea** [comment] 2018-11-24 15:41
@matinict , are you solve your issue above?

**Comment by kipotlea** [comment] 2018-11-24 15:49
@matinict . 
the root causes of the problem are because of wrong writing in Api.php. 
try to change  `__contstruct` to `__construct`

**Comment by baddwin** [comment] 2018-11-27 13:33
> @matinict .
> the root causes of the problem are because of wrong writing in Api.php.
> try to change `__contstruct` to `__construct`

well done, glad to know that you've discovered the root of issue @kipotlea :+1: 

please submit pull request for it to close the issue, thanks

**Closed as completed** 2020-01-07 12:53 UTC
